# Generated by Django 4.1.7 on 2023-04-17 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('riddle', models.CharField(blank=True, max_length=250)),
                ('answer', models.CharField(blank=True, max_length=250)),
                ('secondary_answer', models.CharField(blank=True, default='something random with oqeiwuweywe', max_length=250)),
                ('question_type', models.CharField(choices=[('trivia', 'TRIVIA'), ('riddle', 'RIDDLE'), ('none', 'NONE'), ('bunq history', 'BUNQ HISTORY')], default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.TextField(blank=True)),
                ('correct', models.BooleanField()),
                ('adam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='questions.question')),
            ],
        ),
    ]
