# Generated by Django 4.1.7 on 2023-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_question_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('trivia', 'TRIVIA'), ('riddle', 'RIDDLE'), ('none', 'NONE')], default='none', max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='secondary_answer',
            field=models.CharField(blank=True, default='something random with oqeiwuweywe', max_length=250),
        ),
    ]
