# Generated by Django 4.1.7 on 2023-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('trivia', 'TRIVIA'), ('riddle', 'RIDDLE'), ('none', 'NONE'), ('bunq history', 'BUNQ HISTORY')], default='none', max_length=20),
        ),
    ]
