# Generated by Django 4.1.7 on 2023-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
