# Generated by Django 4.1.7 on 2023-04-17 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_alter_answers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='adam',
        ),
        migrations.AddField(
            model_name='answers',
            name='adam',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
