# Generated by Django 4.1.7 on 2023-04-17 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_remove_answers_adam_answers_adam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='adam',
        ),
        migrations.AddField(
            model_name='answers',
            name='adam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
